import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hotel from '../components/Hotel'


export default function Home() {
  return (
    <div className="overflow-x-hidden" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Hotel/>

    </div>
  )
}
